language: objective-c
osx_image: xcode8.2

script:
    - xcodebuild -version -sdk
    - xcodebuild clean test -project Deque.xcodeproj -scheme Deque -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES

